### ISSUE TITLE
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer

### ISSUE THREAD

**Issue by acreeper111** [microsoft/minecraft-scripting-samples#12]
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (D:\bedev\ts-starter-complete-cotta\node_modules\gulp-typescript\node_modules\source-map\lib\read-wasm.js:8:13)
    at wasm (D:\bedev\ts-starter-complete-cotta\node_modules\gulp-typescript\node_modules\source-map\lib\wasm.js:25:16)
    at D:\bedev\ts-starter-complete-cotta\node_modules\gulp-typescript\node_modules\source-map\lib\source-map-consumer.js:264:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5

**Comment by mammerla** [comment]
Should be fixed now with an updated dependency.  Sorry for the delay.
